exchange: binance
api_key: your_api_key_here
api_secret: your_api_secret_here
rugcheck_api_key: your_rugcheck_api_key_here
symbols:
  - BTC/USDT
  - ETH/USDT
timeframe: 1h
strategy:
  name: multiplier_sell
max_allocation_percent: 10.0
sell_percent_2x: 50.0
sell_percent_3x: 100.0
gmgn_api:
  api_host: https://gmgn.ai
  chain: sol
  rpc_endpoint: https://api.mainnet-beta.solana.com
  private_key: your_private_key_base58_here
telegram:
  bot_token: your_telegram_bot_token_here
  chat_id: your_telegram_chat_id_here